# Site settings
title: Defuse the Situation

# Theme settings
theme: jekyll-theme-minimal

# YAML Front Matter settings
yaml_front_matter: true

nav:
  - name: Home
    link: /defuse-the-situation
  - name: About
    link: about
  - name: Bill of Materials
    link: bom
  - name: Design
    link: design
  - name: Process
    link: process